sync_changes_to_github:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "adamlui/ai-web-extensions"
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://gitlab.com/adamlui/ai-web-extensions.git
    - git push --force -o ci.skip https://${GITHUB_SYNC_PAT}@github.com/adamlui/ai-web-extensions.git HEAD:main
